### ISSUE TITLE
Different colors for combinations of Debuffs?

### ISSUE THREAD

**Issue by jamby** [rljohn/kuinameplates-target-helper#1]
I posted on [CurseForge](https://www.curseforge.com/wow/addons/kuinameplates-target-helper) but wanted to post here for visibility.

Is there any way to do 1 color for a specific debuff, but a different color if 2 debuffs exist?

For instance: Enhancement Shamans want Flame Shock on targets and then want to Lava Lash targets to cause the debuff Lashing Flames so they deal more damage. So I'm attempting to have:

1 color for just flame shock
1 color for just lashing flame
1 color for both flame shock and lashing flame on same target.

**Comment by rljohn** [comment]
Interesting concept. I might see if I can put together something for that.

**Comment by rljohn** [comment]
This is now supported.
