### ISSUE TITLE
Failed to import.

### ISSUE THREAD

**Issue by ShowKris1** [rljohn/kuinameplates-target-helper#11]
Hi,
while i'm try to import an profil, it doesnt allow me to click on "import" button.
![image](https://user-images.githubusercontent.com/119816568/205515051-797b7b6b-66d6-4e76-a734-a86d68edf187.png)

The "import" button is like no available.
does someone have the same issue ? also, when im tryin to use the "Enable Shared Settings" i dont know who is the master data. It erase all my Target Helper i setup before.

Thank you for any feedback.
Regards.

**Comment by rljohn** [comment]
I will look into ways of improving the UI here.

**Comment by rljohn** [comment]
UI improvements in 1.2.8 for the import/export panel. I'll update the popups with shared settings later to help indicate which profile you're switching to.

**Comment by ShowKris1** [comment]
@rljohn 
Amazing. Thank you so much for your feedback and help !
