### ISSUE TITLE
Cvar question

### ISSUE THREAD

**Issue by NorTroll** [rljohn/kuinameplates-target-helper#12]
If enabling cvar modification in Kui Target Helper, should i disable in kui nameplates core? enable it but make sure they both match? etc? there are some options in kui target helper i do not have in core, and vise versa. 

-NorTroll

**Comment by rljohn** [comment]
We only adjust values when you tweak the sliders, so it should be safe to enable both. I also recommend Advanced Interface Options for modifying any CVAR.
