### ISSUE TITLE
Using Unit filter has caused hiding problem

### ISSUE THREAD

**Issue by BuurmanDeBuurman** [rljohn/kuinameplates-target-helper#14]
After using the Unit Filter to test the functions, then subsequently clearing all test filters. The name filter is hiding name-only names that I don't want hidden. 

I used 'Shikaar Hunter' and 'Ohn'ir Battleguard' as tests which I cleared. Subsequently Sansok Khan's name tag is completely gone. 

Disabling the addon removes the problem, turning the addon back on returns the problem.

Shame the addon got the issues it does because the concept of the addon does perfectly align with what I want out of it.

**Comment by BuurmanDeBuurman** [comment]
I however don't see what in the settings of this addon would cause to hide 'Khanam Matra Sarest' or 'Sansok Khan' name-only nameplates. Yet, they show without the addon and don't with the addon.

**Comment by BuurmanDeBuurman** [comment]
Any answer on this? Names like Alexstrasza simply don't show by default with this addon.

**Comment by BuurmanDeBuurman** [comment]
It appears like the addon is not dealing well with name-only mode for some NPC's because the nameplates do show when toggling name-only mode on and off.

**Comment by rljohn** [comment]
I'll take a look. Where is the name only mode option and what is the easiest npc to test on?

**Comment by rljohn** [comment]
Tested on Alextraza, issue was actually with the elite border code. Fixed w/ version 1.2.11
