### ISSUE TITLE
Latent Poison tracking for Hunters

### ISSUE THREAD

**Issue by Michorov** [rljohn/kuinameplates-target-helper#16]
Currently there is an option to track Serpent Sting but via the talent Poison Injection the Serpent sting applies Latent Poison stackable debuff.

I've added the debuff to KuiSpellListConfig and I can see it on the nameplates however there is no way to color track it
![image](https://user-images.githubusercontent.com/49190977/221367732-7788bc8e-f91c-4b5b-90b5-0c63c9c85a99.png)
![image](https://user-images.githubusercontent.com/49190977/221367758-39cd9a38-607b-4806-8d65-6ed9aed24931.png)
![image](https://user-images.githubusercontent.com/49190977/221367806-1590f690-5826-4b94-af48-b1082c38f59a.png)

Also would be fantastic if there is an option to track it via color based on stacks. (i.e color changes with 8 or more stacks)

**Comment by rljohn** [comment]
Thanks I'll look into this.

**Comment by rljohn** [comment]
I don't have a max level hunter to test with, but using the spell ID from your screenshot above (378015) I've added support in build 1.2.14. Please let me know if that helps.

**Comment by Michorov** [comment]
Works as expected to track it. 

Is it possible to add some way to pick the color to show above certain amount of stacks?
The debuff does X amount of damage per stack and it's activated by using Mongoose Bite which is single target, so it requires rotating targets to proc it 1 by 1.
Having it show above a certain amount of stacks can work as a reminder to not overcap.

As I currently see there is no such functionality in the addon so if it's unrealistic you can close the ticket as it's working as any other debuff tracking right now

**Comment by rljohn** [comment]
What is the stack count you'd expect to need to track as a minimum for activating the color? Its a lot harder for me to add customization options, but if I can add some "good" default behavior.

**Comment by Michorov** [comment]
I goes up to 10 stacks roughly 1 per second (it procs from serpent sting hits so scales with haste) I think 7 stacks wound be a nice amount to react so it doesn't cap on 10
