### ISSUE TITLE
game freeze when joining a raid group

### ISSUE THREAD

**Issue by nukhub** [rljohn/kuinameplates-target-helper#17]
hey,

so i have this issue, when i join a group, the more the player the more the game freezes (like for 10sec when joining a full raid), also, when someone im in group with change spec, small freeze too.

this only happen with kui target helper loaded
i tested with only knp & target helper loaded, still freezes, then i disable target helper, no freeze -no other addon loaded-

i think maybe my config file has gotten too big with new seasons and all (thanks a lot for the addon btw, so usefull to me and all my team mates -who also freeze because they use my config-)

anyway, i'll join my config, hope you can help !

https://cdn.discordapp.com/attachments/736271525803589703/1111717603006750770/Kui_Nameplates_TargetHelper.lua
this is a global profile

**Comment by rljohn** [comment]
If you can -- open the 'Profiles' panel in the addon config and use the Export button to export a string?

**Comment by rljohn** [comment]
![image](https://github.com/rljohn/kuinameplates-target-helper/assets/2583216/9f321ef6-c865-4ca7-90bc-49cfab258d16)

**Comment by rljohn** [comment]
Please check out the 1.2.20 Beta build:
[Kui TargetHelper 1.2.20 Beta](https://legacy.curseforge.com/wow/addons/kuinameplates-target-helper/files/4553757)

Let me know if that is an improvement. I found a couple performance optimizations after importing your config.

**Comment by nukhub** [comment]
you are the best, problem solved ! thanks a lot

**Comment by rljohn** [comment]
Great. I'll play with those changes over the weekend and send out a release if no issues pop up.
