### ISSUE TITLE
Hpal glimmer of light

### ISSUE THREAD

**Issue by sofienefenniche123** [rljohn/kuinameplates-target-helper#19]
Hi, I wanted to know if it was possible to add a debuff colors for 'glimmer of light' more precisely

**Comment by rljohn** [comment]
Yeah I can get that added this week

**Comment by sofienefenniche123** [comment]
ty <3

**Comment by rljohn** [comment]
https://github.com/rljohn/kuinameplates-target-helper/commit/3044ef09b09fe085ad8cab51ba72b88e783d988a

**Comment by rljohn** [comment]
I received a bug report that this wasn't working, but version 1.2.27 should have a proper fix.
