### ISSUE TITLE
auras.lua always overrides my additions upon update

### ISSUE THREAD

**Issue by wwbrandon** [rljohn/kuinameplates-target-helper#20]
Hello,

I play Discipline Priest and the best best debuff for me to track with colors is Schism- I've been adding it in manually every refresh but was wondering if you could just add that into your baseline so I don't have to keep doing it?

Tracking purge the wicked doesn't make nearly as much sense as tracking Schism. Also, can you add a feature to change the nameplate strata?

Thanks

**Comment by rljohn** [comment]
Yeah man, I can get Schism added. I'd have to look into Strata, can you
describe your use case?

**Comment by wwbrandon** [comment]
I have my whole screen shift to purple-ish hue when I use Shadow Covenant with a WA. I have the WA set to the lowest strata possible, but your nameplates always appear behind all WAs. I'd rather see the colors of my nameplates always unaltered and on top of WAs.

JustDiscipline on YouTube if you want an example.

**Comment by rljohn** [comment]
Can you link me the weakaura? I'd need to take a closer look since it's the
base kuinameplates we'd modify the frame strata for.

Ill get the schism fix in early this week and take a look at the strata
issue when I have the time.

**Comment by wwbrandon** [comment]
Thank you for looking, I tried everything I knew before reaching out. Here is a link to my WA- you'll notice the nameplates fall behind it.

https://wago.io/v8G_go4P6

**Comment by wwbrandon** [comment]
Any updates on changing the addon's strata level???

**Comment by rljohn** [comment]
No sorry. Been busy outside the game the last couple weeks and have a few todos on another addon to fix first. I'll keep this issue open.

**Comment by wwbrandon** [comment]
Thank you, I appreciate it. I promote your addon in all of my youtube videos. KUI > Plater any day!

**Comment by rljohn** [comment]
![image](https://github.com/rljohn/kuinameplates-target-helper/assets/2583216/7ebe1852-8925-4e52-9f2e-c1070cf59e6f)

I'm not sure I understand what's rendering incorrectly. I downloaded the weakaura but everything seems ok?

**Comment by rljohn** [comment]
I dug into this a little more, set the overlay opacity to 100% to verify the issue. The nameplates are parented to the WorldFrame which runs at 'BACKGROUND' frame strata by default.

This is the code that fixed it for me:
`/script WorldFrame:SetFrameStrata('LOW');`

With the fix:
![image](https://github.com/rljohn/kuinameplates-target-helper/assets/2583216/67e012ad-b22a-4bec-abd1-33dd6452841f)

Without the fix:
![image](https://github.com/rljohn/kuinameplates-target-helper/assets/2583216/3b379544-eb0f-41f0-bddd-6570719bc467)

You can maybe setup a weakaura to run this on login?

**Comment by wwbrandon** [comment]
Omg... thank you so much for finding the solution even tho it was outside your addon. This will work just fine me... I never considered nameplate strata would be controlled by a CVAR.

Thanks, 
Disc

**Comment by wwbrandon** [comment]
Hey again, sorry to bring it up again but the script isn't a perfect solution- it makes the nameplates interact with each other differently and no longer puts your target to the top of the bunch.

I tried using different strata levels with the script but that didn't work for me, can you think of another solution? No sweat if not!

**Comment by rljohn** [comment]
When in game, type `/fstack` to open up the hierarchy of frames.

You can then run /script FrameName:SetFrameStrata or other frame API commands to fiddle with it. 
https://wowpedia.fandom.com/wiki/API_Frame_SetFrameLevel

I'm not sure which combination is required for this background weakaura to work, but its probably some combination of lowering its frame to the bottom and raising nameplates to the top.
