### ISSUE TITLE
Serpent Sting does not color nameplates for survival hunters

### ISSUE THREAD

**Issue by corcaroli** [rljohn/kuinameplates-target-helper#21]
Hello,
currently applying [Serpent Sting](https://www.wowhead.com/spell=271788/serpent-sting) as a survival hunter does not change nameplate color. (It does work correctly for marksmanship hunters though.)
KSLC whitelist:
<img src="https://i.imgur.com/hDRlXkV.png">
KUI target helper debuff options:
<img src="https://i.imgur.com/ENBzyhq.png">
Actual nameplate with Serpent Sting applied:
<img src="https://i.imgur.com/0X7mLLp.png">

Also i am not sure survival hunters have this [Lacerate](https://www.wowhead.com/spell=185855/lacerate) ability anymore. According to [Wowpedia](https://wowpedia.fandom.com/wiki/Lacerate_(hunter_ability)), it was removed in patch 8.0.1.

**Comment by rljohn** [comment]
Great feedback. I'll get this sorted.

**Comment by rljohn** [comment]
https://github.com/rljohn/kuinameplates-target-helper/commit/5b4f15d0a2d9183b9d47d8d306b7f10fe907897f
