### ISSUE TITLE
Execute Range x Target Helper

### ISSUE THREAD

**Issue by wwbrandon** [rljohn/kuinameplates-target-helper#3]
Really love this addon... wow. Anyway, I'm using the coloring plugin and it overrides execute range colors. Not sure if that is intended, but I think still seeing execute range interact with custom colors would be better!

Thanks for the addon!

**Comment by rljohn** [comment]
I'll likely add a setting on the UI to disable during execute range, but the names will still use the color to help identify targets.

**Comment by wwbrandon** [comment]
Seems like a fair compromise! Personally, I wouldn't want names to change color! Thanks for listening to my feed back!

**Comment by rljohn** [comment]
After further review, I've noted that the KUI execute plugin runs at Priority 4. If you set the Target Helper plugin priority to 1, 2 or 3, we will no longer override the execute color.

This can be done from the main Target Helper panel.

**Comment by wwbrandon** [comment]
Wow, thanks a ton for the tip. Appreciate it!
