### ISSUE TITLE
WoW Patch 11.0.2.56110 and Kui TargetHelper_1.5.2_release

### ISSUE THREAD

**Issue by fraerie** [rljohn/kuinameplates-target-helper#35]
LUA error calling deprecated API call

7x ...eKui_Nameplates_TargetHelper/auras_panel.lua:376: attempt to call global 'GetSpellInfo' (a nil value)
[string "@Kui_Nameplates_TargetHelper/auras_panel.lua"]:376: in function <...eKui_Nameplates_TargetHelper/auras_panel.lua:369>
[string "=[C]"]: in function `foreach'
[string "@Kui_Nameplates_TargetHelper/auras_panel.lua"]:369: in function <...eKui_Nameplates_TargetHelper/auras_panel.lua:350>
[string "=[C]"]: in function `foreach'
[string "@Kui_Nameplates_TargetHelper/auras_panel.lua"]:350: in function `AddClassAuras'
[string "@Kui_Nameplates_TargetHelper/auras_panel.lua"]:429: in function <...eKui_Nameplates_TargetHelper/auras_panel.lua:427>
[string "=[C]"]: in function `foreach'
[string "@Kui_Nameplates_TargetHelper/auras_panel.lua"]:427: in function `RefreshClassAuras'
[string "@Kui_Nameplates_TargetHelper/config.lua"]:332: in function `Initialised'
[string "@Kui_Nameplates/addon.lua"]:197: in function <Kui_Nameplates/addon.lua:154>

Locals:
k = 1
v = 164815
(*temporary) = nil
(*temporary) = 164815
(*temporary) = "attempt to call global 'GetSpellInfo' (a nil value)"
first = true
abilityString = ""
abilitySum = 164815
icon1 = nil
icon2 = nil
icon3 = nil
icon4 = nil

**Comment by rljohn** [comment]
Noted, I will fix this tonight. Thank you!

**Comment by rljohn** [comment]
https://github.com/rljohn/kuinameplates-target-helper/commit/ed3d98017ade4f374fcd1e51db437f71ad0bfd92
