### ISSUE TITLE
request : add npc by NpcID

### ISSUE THREAD

**Issue by nukhub** [rljohn/kuinameplates-target-helper#4]
would be easier to add mobs from wowhead or MDT (and in french client some mobs have male/female names on the same ID)

anyway, thanks for your work, very nice addon !

**Comment by rljohn** [comment]
The issue with NPC ID is they are only relevant to UnitGUID , which requires a target to have been seen by the player already. This makes the configuration panel harder to setup for users.

I do recognize an issue with being able to share profiles, so I will be working on an import/export function for targets to make them easier to share.

I'll also be adding buttons to quickly load important S4 and Dragonflight S1 targets in an upcoming build.

**Comment by rljohn** [comment]
I learned how to do this recently and will include npc id in the next build.

**Comment by nukhub** [comment]
awesome, ty !

**Comment by rljohn** [comment]
the latest beta build has this fix. unfortunately i had some hardware issues over the weekend so I haven't been able to fully commit to pushing a Release build.

Type in an NPC ID and if the NPC exists, it should convert to name and add it to your filter.

**Comment by nukhub** [comment]
thank you very much, will make things a lot easier for me

**Comment by rljohn** [comment]
1.2.5
