### ISSUE TITLE
minor extension to auras.lua - "Festering Wound" for Unholy DKs

### ISSUE THREAD

**Issue by Grimhead** [rljohn/kuinameplates-target-helper#6]
Maybe not real issue, more like usefull minor upgrade to this _greate_ addon

Could you add "Festering Wound" to Unholy DK in auras.lua? 
I think more DKs would appreciate it in 10.0.2 :)

	[252] = { 	-- Unholy DK
		191587,	-- 	Viralent Plague
		194310 	--	Festering Wound
	},

GH.

**Comment by rljohn** [comment]
Yes for sure

**Comment by rljohn** [comment]
Fixed in 1.2.3 :)
