### ISSUE TITLE
Outdated debuff list for Subtlety Rogue (unfixed by adding/removing in Spell list)

### ISSUE THREAD

**Issue by pxb0** [rljohn/kuinameplates-target-helper#7]
Hello. Just wanted to bring it to your attention that the list of debuffs in the debuff color section of the addon is very outdated for Subtlety Rogue. All it features is a spell called Nightblade which hasn't been in the game since Battle for Azeroth. I tried to fix the problem manually by following the advice of adding the spells to KUI Spell List, but this does not seem to fix the problem, the only spell remaining in the list is Nightblade. Thank you for your time and attention concerning this issue.

**Comment by rljohn** [comment]
I will do my best to update Sub Rogue soon. If you have a list of useful debuffs to track let me know and I will add them.

**Comment by jbondpdx** [comment]
I would also love to see combined debuffs for rogue; I'm playing assassination, and it would be super helpful to show when I have rupture _and_ garrote on the target.

**Comment by pxb0** [comment]
For Subtlety it shouldn’t be too many. Rupture and Find Weakness are the two relevant debuffs the spec has that would be nice to have the option to modify bar colors by. You can also potentially add on Flagellation and Sepsis to be able to track your priority target easier.

**Comment by rljohn** [comment]
I will have all of this updated later today before launch. 

One note is that Flagellation will need to be added to the KuiSpellConfig as it doesnt' appear on nameplates by default.

**Comment by pxb0** [comment]
Excellent, thank you sir.
