### ISSUE TITLE
Debuff Collors (MM) Hunters

### ISSUE THREAD

**Issue by richyvee** [rljohn/kuinameplates-target-helper#9]
Hey, 
It would be awsome to have debuff colors enabled for (MM) Hunters.

My suggestion would be: 
.) Targets affected by Serpent Sting should have the nameplate turn green.
wether it be through the Hunter Talent (ID: 271788) or Serpentstalkers Trickery (ID: 378888)
.) Targets affected by Razor Fragments (ID 384790) should turn orange

Happy to supply more suggestions for Hunters when it comes to debuff colors, those are just the two most important ones for me personally.

Hope you enjoy DF launch.

**Comment by rljohn** [comment]
Cheers! I will get this updated sometime in the next day or so, enjoy the launch!

**Comment by rljohn** [comment]
Sorry for the delay, taking a look shortly.

**Comment by rljohn** [comment]
Release 1.2.7

**Comment by richyvee** [comment]
heyo, thanks a lot for the time you put in during release week!
I tested it on some random mobs, works perfect so far. 

since BM and SV can also specc into serpent sting, maybe you wanna add the serpent tracking for those two speccs too.
